"""poner True a supplier_id

Revision ID: 50486861f390
Revises: 46edf5b6ac9f
Create Date: 2025-06-26 10:17:19.430851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50486861f390'
down_revision: Union[str, None] = '46edf5b6ac9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_payment_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_full_name_snapshot', sa.String(), nullable=False),
    sa.Column('employee_identity_document_snapshot', sa.String(), nullable=False),
    sa.Column('employee_position_snapshot', sa.String(), nullable=True),
    sa.Column('employee_department_snapshot', sa.String(), nullable=True),
    sa.Column('school_name_snapshot', sa.String(), nullable=False),
    sa.Column('school_rif_snapshot', sa.String(), nullable=False),
    sa.Column('payment_date_snapshot', sa.Date(), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('total_earnings_ves', sa.Float(), nullable=False),
    sa.Column('total_deductions_ves', sa.Float(), nullable=False),
    sa.Column('net_pay_ves', sa.Float(), nullable=False),
    sa.Column('payment_breakdown_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_payment_id'], ['employee_payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_payment_id')
    )
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslips_id'), ['id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_suppliers_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(None, 'expense_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_suppliers_category_id'))
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslips_id'))

    op.drop_table('payslips')
    # ### end Alembic commands ###
